AutoEncoderSavePath = "/Users/libo/PycharmProjects/Flask_web_recommender/recommender_model/parameter_model/model_AutoEncoder_"
RNNSavePath = "/Users/libo/PycharmProjects/Flask_web_recommender/recommender_model/parameter_model/model_RNN_"
GRUSavePath = "/Users/libo/PycharmProjects/Flask_web_recommender/recommender_model/parameter_model/model_GRU_"
NewsDataSetPath = "ArticleRecord.txt"
HistoryDataSetPath = "HistoryRecord.txt"
StopWordPath = "/Users/libo/PycharmProjects/Flask_web_recommender/crawler/stop_word_chs.txt"
UserStatePath = "/Users/libo/PycharmProjects/Flask_web_recommender/recommender_model/UserStates.txt"
RecommendedPath = "/Users/libo/PycharmProjects/Flask_web_recommender/recommender_model/parameter_model/Recommended.txt"